name: B2

on:
  schedule:
    - cron: '0 */1 * * *' # يشغل الكود كل ساعة
  push: # عند كل عملية دفع جديدة
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "your-username"
          git config user.email "your-email@example.com"
          git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/your-username/your-repo.git

      - name: Run B2 Tasks
        run: |
          echo "Executing simple auto-refresh tasks..."
          git pull
          git push
